name: Deploy 
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy to server using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/userbe10/BACK-END
            git pull origin main
            docker stop bookstoreContainer
            docker rm bookstoreContainer
            docker rmi bookstore-api
            docker build -t bookstore-api:latest .
            docker run -d -p 9000:8000 -e Username=${{ secrets.DB_USERNAME }} -e Password=${{ secrets.DB_PASSWORD }} -e Port=${{ secrets.DB_PORT }} -e Address=${{ secrets.DB_HOST }} -e Name=${{ secrets.DB_NAME }} -e SECRET=${{ secrets.SECRET }} -e SERVERPORT=${{ secrets.SERVERPORT }} --name bookstoreContainer bookstore-api:latest
            # docker run -d -p 9000:8000 -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=${{ secrets.DB_NAME }} -e SECRET=${{ secrets.SECRET }} -e SERVERPORT=${{ secrets.SERVERPORT }} --name bookstoreContainer bookstore-api:latest
